name: autograding

on:
  push:
    branches:
      - main  # Run tests and deploy on push to main.
  pull_request:
    branches:
      - main  # Run tests on PRs.

jobs:
  build-and-test:
    if: github.ref != 'refs/heads/gh-pages'  # Skip if on gh-pages...
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install package dependencies
        run: npm install

      - name: Execute test cases
        run: npm test

  deploy:
    needs: build-and-test  # Only deploy if tests pass.
    if: github.ref == 'refs/heads/main'  # Only deploy from main.
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages
